### ISSUE TITLE
delete_pull_zone not functional

### ISSUE THREAD

**Issue by amanelis** [MaxCDN/rws-bugs#1]
When I call the Delete Pull Zone method, here is the exact log output. Nothing gets removed

"DELETE /amanelis/zones/pull.json/69056? HTTP/1.1" 200 22 "-" "OAuth gem v0.4.6"

Here is the code I'm using to call the method:
https://github.com/amanelis/netdna2/blob/master/lib/netdna2/zones.rb#L225

Forgive me for the options={} param on the delete, that will be removed on the next commit.

**Comment by jdorfman** [comment]
Thanks @amanelis @dlitvakb will have this fixed by tomorrow.

**Comment by dlitvakb** [comment]
Why dont you use our Ruby gem netdnarws for this??

It might solve you this problem

**Comment by amanelis** [comment]
@dlitvakb your gem has 0 test coverage, can't have mess ups in a production environment, i.e. zones not deleting, updating etc...

**Comment by dlitvakb** [comment]
@amanelis I can upload the test cases but not the fixtures if you want.

The gem is fully functional and is being QA'd frequently to be sure nothing is failing.

Please use it instead of your custom client. Extend it as needed.

The most probable cause of your issue though... is encoding spaces as `+` instead of `%20`, which is a problem we've faced before while writing our gem.

**Comment by eamonnscu** [comment]
@amanelis The gem we provide is there for convenience, but you are absolutely welcome to develop your own :)

There's a recent issue with the RWS API in which the inactive flag is not being properly set to 1 during the DELETE request, though all other actions are properly taking place. The fix for this is currently in QA and should be pushed live tomorrow. I will update you once the update is made but I believe this will resolve the issue you are having.

**Comment by amanelis** [comment]
@pascalscu thanks, appreciate the info.

**Comment by eamonnscu** [comment]
@amanelis Just uploaded the fix. Let me know how it works

**Comment by amanelis** [comment]
Worked. Thanks!

On Thu, Dec 6, 2012 at 11:24 PM, pascalscu notifications@github.com wrote:

> @amanelis https://github.com/amanelis Just uploaded the fix. Let me
> know how it works
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netdna/rws-bugs/issues/1#issuecomment-11121270.

## 

Alex Manelis
832.483.4112
@amanelis

**Comment by eamonnscu** [comment]
Welcome!
