### ISSUE TITLE
Recent Changes To The REST API

### ISSUE THREAD

**Issue by hunterbm** [MaxCDN/rws-bugs#4]
I have noticed recent changes to the CDN API, primarily the addition of 'customdomains' and the 'cdn_url' response changing to the 'ssl_url' response value when shared SSL is enabled.  I am working to update  our API implementation to best support the current changes, and hopefully future intent as I'm not sure what exists in its current state is completed.  The 'cdn_url', 'tmp_url', and 'ssl_url' of 'getZone' are no longer listed as documented responses under the API documentation, should these considered to be depreciated and later to be removed ?

While the 'ssl_url' is listed under 'customdomains' as type 'pull-ssl' (at least for pull zones, which is what I use) and custom domains with type 'null' , the temp url is not listed under custom domains at all.  Will this always be the case ?

It might be nice to actually label the 'custom domains' as 'pull-custom' and equally include the 'tmp_url' as 'pull-temp', and in the case of a custom ssl 'pull-customssl' or similar, so that all potential URLS are made available.

Additionally, it would be nice if 'customdomains' included as a sub-array of the getZone request to circumvent the need for a secondary request for the initial population of zone data to on page panels.

Furthermore, it would equally be nice if you guys would at the very least inform us somehow, either via blog or e-mail notification, or otherwise that changes have occurred to the API, especially when they can fault an application (as the above / recent change has).  Ultimately, a versioning protocol would be ultimately beneficial.

I would very much appreciate an answer to the above questions and concerns.

**Comment by eamonnscu** [comment]
Hey Hunter,

Those are actually not recent changes, the API has always worked like that. Here's an explanation of those properties and when they return what:

tmp_url: This property will always be returned with the same value (zonename.companyalias.netdna-cdn.com)

ssl_url: This property will only be returned if SharedSSL is enabled on the zone. In this case its value will be (zonename-companyalias.netdna-ssl.com)

cdn_url: This property will always be returned (even with SharedSSL enabled) and will be one of two values. If you have any custom domains, it will return your first custom domain. Otherwise it will return your tmp_url. This property is likely to be removed in the near future.

 The tmp_url will never show under custom_domains as it is the default URL for the zone. Good suggestion regarding returning the custom domains as an element of the returned zone. We will add that to our dev backlog and update you once it has been made available.

Sorry about the confusion regarding these not showing up in the documentation, we will get those added. All of our updates regarding the API can be found on our blog at http://blog.netdna.com/category/developer/. There was no mention of these properties since their behavior hasn't changed for months.

Please let me know if I can provide further details regarding anything.

**Comment by hunterbm** [comment]
Given your response, I suppose the change / problem I am experiencing is then potentially a bug with the API.

The 'cdn_url' returned is the ssl_url when shared ssl is on, this has started happening in zones which I deploy in the last 2-3 weeks.  I had been using the 'cdn_url' as the domain name to hit for non-ssl transactions.  I will send a zone_id for reference to Justin D. and hopefully he can pass it on to you guys.

**Comment by eamonnscu** [comment]
Sorry poor wording on my end.

The ssl_url is treated as a custom domain when enabled. Thats why it is returning in the cdn_url property of your zone (it is your first custom domain).

You can serve non-secure content through this URL, just change the scheme from https:// to http://

**Comment by hunterbm** [comment]
Well regardless, this didn't used to happen and is a recent, undocumented change.  In fact older zones deployed still report the cdn_url as being the custom defined domain, with shared SSL turned on.

**Comment by eamonnscu** [comment]
It would depend on which occurred first, creating the custom defined domain or enabling SharedSSL

**Comment by hunterbm** [comment]
Previously it didn't.

**Comment by hunterbm** [comment]
NOTE: This could be more to do with recent changes to the control panel and not the API itself, previously (possibly as you suggest a change in order of operation), one could enable / disable / etc ... the SSL shared feature without affecting the cdn_url properly.

**Comment by eamonnscu** [comment]
Depending on the order of operations, enabling / disabling SharedSSL may or may not affect the cdn_url property.

The custom domains are stored in a table where they are linked by zone id, and the cdn_url currently returns whatever the first record in this table is (or the tmp_url if the zone has no records in the table) Enabling / disabling SharedSSL will add or remove a record on this table for your zone. So if a custom defined domain is the first record, enabling and disabling Shared SSL will not affect the cdn_url property. Otherwise it will affect this value.

We willll look into removing the cdn_url property and instead return an array of the custom domains with the zone. Hope the information above helps to clarify things a little further. Let me know if theres something I can explain more in depth, and I will keep you updated regarding returning the customdomains with the zone (as well as post to the blog when it is available)
